name: bootkit-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull source
        uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          command -v wget || ./layers/minbase/pkgtool install wget
          wget --progress=dot:mega -O ./stacker \
              https://github.com/project-stacker/stacker/releases/download/v1.0.0-rc1/stacker
          chmod 755 stacker
      - name: build bootkit
        run: |
          PATH="$PWD:$PATH" make build
      - name: build pkg/oci-iso
        run: |
          PATH="$PWD:$PATH" make pkg-build
